# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Dan Urbanowicz", value: "dan_urbanowicz" }
          - { label: "John Doe", value: "john_doe" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    # PAGES
  # - name: "page"
  #   label: "Page"
  #   folder: "pages"
  #   sort: "title:asc"
  #   create: false
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
  #     - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  #     - {label: "Permalink", name: "permalink", widget: "hidden"}
  #     - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
  #     - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
  #     - {label: "Body", name: "body", widget: "markdown", required: false}
    #imported from hugo
  - name: "pages"
    label: "Pages"
    files:
      - file: "pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Layout", name: "layout", widget: hidden, default: "home"}
          - {label: "Permalink", name: "permalink", widget: string, default: "/"}
          - {label: "homepage Title", name: title, widget: string}
          - {label: "homepage Subtitle", name: "subtitle", widget: string}
          - {label: "homepage Image", name: image, widget: image}
          - {label: "homepage Button text", name: button_text, widget: string}
          - {label: "homepage Button link", name: button_link, widget: string}
          - {label: "homepage Video WEBM", name: video_webm, widget: string}
          - {label: "homepage Video MP4", name: video_mp4, widget: string}
          - {label: "Manual PDF", name: "manual_pdf", widget: "file", default: "/uploads/" , media_library:"/uploads/", config:, multiple: true}
          - {label: "homepage Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "pages/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "pages/about.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}

